spring:
  application:
    name: ribbon
server:
  port: 9000

#高可用
eureka:
  client:
    service-url:
       defaultZone:
               #http://localhost:8761/eureka/
               http://server1:8760/eureka/,http://server2:8761/eureka/