spring:
  application:
    name: server
server:
  port: 8761
eureka:
  instance:
    hostname: server1
    #续约时间
    lease-renewal-interval-in-seconds: 30
    #失效时间
    lease-expiration-duration-in-seconds: 90
    #改名
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone:
         http://${eureka.instance.hostname}:8760/eureka/




