
#高可用
eureka:
  client:
    service-url:
       defaultZone:
               #http://localhost:8761/eureka/
               http://server1:8760/eureka/,http://server2:8761/eureka/
server:
  port: 8762
  #port: 8763
spring:
  application:
    name: client
